/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/models/64f1a714fe61576b46f27ca2.glb -o src/components/Avatar.jsx -k -r public
*/

import { useAnimations, useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import { button, useControls } from "leva";
import React, { useEffect, useRef, useState } from "react";

import * as THREE from "three";
import { useChat } from "../hooks/useChat";

const facialExpressions = {
  default: {},
  
  // Ekspresi senyum yang lebih natural
  smile: {
    browInnerUp: 0.1,
    eyeSquintLeft: 0.25,
    eyeSquintRight: 0.25,
    noseSneerLeft: 0.08,
    noseSneerRight: 0.08,
    mouthPressLeft: 0.3,
    mouthPressRight: 0.3,
    mouthSmileLeft: 0.4,
    mouthSmileRight: 0.4,
    mouthDimpleLeft: 0.2,
    mouthDimpleRight: 0.2,
    cheekSquintLeft: 0.15,
    cheekSquintRight: 0.15,
  },
  
  // Ekspresi lucu yang lebih ekspresif
  funnyFace: {
    jawLeft: 0.5,
    mouthPucker: 0.4,
    noseSneerLeft: 0.8,
    noseSneerRight: 0.3,
    mouthLeft: 0.8,
    cheekPuff: 0.7,
    mouthDimpleLeft: 0.5,
    mouthRollLower: 0.25,
    mouthSmileLeft: 0.4,
    mouthSmileRight: 0.4,
    eyeWideLeft: 0.3,
    eyeWideRight: 0.3,
  },
  
  // Ekspresi sedih yang lebih halus
  sad: {
    mouthFrownLeft: 0.8,
    mouthFrownRight: 0.8,
    mouthShrugLower: 0.6,
    browInnerUp: 0.4,
    eyeSquintLeft: 0.6,
    eyeSquintRight: 0.65,
    eyeLookDownLeft: 0.4,
    eyeLookDownRight: 0.4,
    jawForward: 0.8,
    browDownLeft: 0.3,
    browDownRight: 0.3,
  },
  
  // Ekspresi terkejut yang lebih realistis
  surprised: {
    eyeWideLeft: 0.4,
    eyeWideRight: 0.4,
    jawOpen: 0.3,
    mouthFunnel: 0.8,
    browInnerUp: 0.9,
    browOuterUpLeft: 0.6,
    browOuterUpRight: 0.6,
    mouthStretchLeft: 0.2,
    mouthStretchRight: 0.2,
  },
  
  // Ekspresi marah yang lebih natural dan halus
  angry: {
    browDownLeft: 0.6,
    browDownRight: 0.6,
    browInnerDown: 0.4,
    eyeSquintLeft: 0.5,
    eyeSquintRight: 0.5,
    eyeLookDownLeft: 0.3,
    eyeLookDownRight: 0.3,
    jawForward: 0.4,
    jawLeft: 0.3,
    mouthShrugLower: 0.6,
    mouthShrugUpper: 0.3,
    mouthFrownLeft: 0.5,
    mouthFrownRight: 0.5,
    noseSneerLeft: 0.4,
    noseSneerRight: 0.4,
    cheekSquintLeft: 0.3,
    cheekSquintRight: 0.3,
  },

  happy: {
    browInnerUp: 0.5,
    browOuterUpLeft: 0.3,
    browOuterUpRight: 0.3,
    eyeSquintLeft: 0.4,
    eyeSquintRight: 0.4,
    mouthSmileLeft: 0.2,
    mouthSmileRight: 0.2,
    jawOpen: 0.1,
    noseSneerLeft: 0.1,
    noseSneerRight: 0.1,
  },
  
  // Ekspresi baru: Bingung
  confused: {
    browInnerUp: 0.6,
    browOuterUpLeft: 0.4,
    browOuterUpRight: 0.4,
    eyeLookUpLeft: 0.3,
    eyeLookUpRight: 0.3,
    mouthFrownLeft: 0.3,
    mouthFrownRight: 0.3,
    jawForward: 0.2,
    noseSneerLeft: 0.2,
    noseSneerRight: 0.2,
  },
  
  // Ekspresi baru: Takut
  scared: {
    browInnerUp: 0.8,
    browOuterUpLeft: 0.7,
    browOuterUpRight: 0.7,
    eyeWideLeft: 0.6,
    eyeWideRight: 0.6,
    mouthFrownLeft: 0.5,
    mouthFrownRight: 0.5,
    jawOpen: 0.2,
    mouthShrugLower: 0.4,
    eyeLookDownLeft: 0.3,
    eyeLookDownRight: 0.3,
  },
  
  // Ekspresi baru: Bangga
  proud: {
    browInnerUp: 0.3,
    browOuterUpLeft: 0.5,
    browOuterUpRight: 0.5,
    mouthSmileLeft: 0.5,
    mouthSmileRight: 0.5,
    jawForward: 0.3,
    chinRaise: 0.4,
    eyeLookUpLeft: 0.2,
    eyeLookUpRight: 0.2,
  },
  
  // Ekspresi baru: Malu
  shy: {
    browInnerUp: 0.4,
    eyeLookDownLeft: 0.6,
    eyeLookDownRight: 0.6,
    mouthSmileLeft: 0.3,
    mouthSmileRight: 0.3,
    mouthDimpleLeft: 0.2,
    mouthDimpleRight: 0.2,
    jawForward: 0.1,
    cheekSquintLeft: 0.1,
    cheekSquintRight: 0.1,
  },
  
  // Ekspresi baru: Lelah
  tired: {
    browInnerUp: 0.2,
    eyeSquintLeft: 0.7,
    eyeSquintRight: 0.7,
    eyeLookDownLeft: 0.4,
    eyeLookDownRight: 0.4,
    mouthFrownLeft: 0.3,
    mouthFrownRight: 0.3,
    jawForward: 0.2,
    browDownLeft: 0.3,
    browDownRight: 0.3,
  },
  
  // Ekspresi baru: Penasaran
  curious: {
    browInnerUp: 0.5,
    browOuterUpLeft: 0.3,
    browOuterUpRight: 0.3,
    eyeLookUpLeft: 0.4,
    eyeLookUpRight: 0.4,
    mouthSmileLeft: 0.2,
    mouthSmileRight: 0.2,
    jawOpen: 0.1,
    noseSneerLeft: 0.1,
    noseSneerRight: 0.1,
  },
};


const corresponding = {
  A: "viseme_PP",
  B: "viseme_kk",
  C: "viseme_I",
  D: "viseme_AA",
  E: "viseme_O",
  F: "viseme_U",
  G: "viseme_FF",
  H: "viseme_TH",
  X: "viseme_PP",
};

let setupMode = false;

export function Avatar(props) {
  const { nodes, materials, scene } = useGLTF("/models/geriarti.glb");
  const { animations } = useGLTF("/models/geriarti-animation.glb");
  const { message, onMessagePlayed, audioInstance } = useChat();
  
  // Initialize all state variables at the top
  const [lipsync, setLipsync] = useState();
  const [blink, setBlink] = useState(false);
  const [winkLeft, setWinkLeft] = useState(false);
  const [winkRight, setWinkRight] = useState(false);
  const [facialExpression, setFacialExpression] = useState("");
  const [animation, setAnimation] = useState(
    animations.find((a) => a.name === "idle_three") ? "idle_three" : animations[0].name
  );

  const group = useRef();
  const { actions, mixer } = useAnimations(animations, group);

  // Animation effect
  useEffect(() => {
    if (!actions || !actions[animation]) {
      console.warn(`Animation "${animation}" not found`);
      return;
    }
    
    const action = actions[animation];
    action.reset()
      .fadeIn(mixer.stats.actions.inUse === 0 ? 0 : 0.5)
      .play();
    const isIdleAnimation = ["animation-idle-three", "animation-idle-one"].includes(animation);
    action.clampWhenFinished = true;
    action.loop = isIdleAnimation ? THREE.LoopOnce : THREE.LoopOnce;
    
    const onFinished = (e) => {
      if (!isIdleAnimation) {
        setAnimation("animation-idle-one");
        setFacialExpression("");
        return;
      }
      
      let nextAnimation;
      switch(animation) {
        case "animation-idle-one":
          nextAnimation = "animation-idle-three";
          break;
        case "animation-idle-three":
          nextAnimation = "animation-idle-one";
          break;
        default:
          nextAnimation = "animation-idle-one";
      }
      setAnimation(nextAnimation);
    };

    mixer.addEventListener('finished', onFinished);
    
    return () => {
      mixer.removeEventListener('finished', onFinished);
      action.fadeOut(0.5);
    };
  }, [animation, actions, mixer]);

  // Message effect
  useEffect(() => {
    if (!message) {
      setAnimation("animation-idle-one");
      setFacialExpression("");
      return;
    }
    
    if (message.animation) {
      setAnimation(message.animation);
    }
    if (message.facialExpression) {
      setFacialExpression(message.facialExpression);
    }
    if (message.lipsync) {
      setLipsync(message.lipsync);
    }
  }, [message]);

  // Blink effect
  useEffect(() => {
    let blinkTimeout;
    const nextBlink = () => {
      blinkTimeout = setTimeout(() => {
        setBlink(true);
        setTimeout(() => {
          setBlink(false);
          nextBlink();
        }, 200);
      }, THREE.MathUtils.randInt(1000, 5000));
    };
    nextBlink();
    return () => clearTimeout(blinkTimeout);
  }, []);

  const lerpMorphTarget = (target, value, speed = 0.1) => {
    scene.traverse((child) => {
      if (child.isSkinnedMesh && child.morphTargetDictionary) {
        const index = child.morphTargetDictionary[target];
        if (
          index === undefined ||
          child.morphTargetInfluences[index] === undefined
        ) {
          return;
        }
        child.morphTargetInfluences[index] = THREE.MathUtils.lerp(
          child.morphTargetInfluences[index],
          value,
          speed
        );

        if (!setupMode) {
          try {
            set({
              [target]: value,
            });
          } catch (e) {}
        }
      }
    });
  };

  useFrame(() => {
    !setupMode &&
      Object.keys(nodes.EyeLeft.morphTargetDictionary).forEach((key) => {
        const mapping = facialExpressions[facialExpression];
        if (key === "eyeBlinkLeft" || key === "eyeBlinkRight") {
          return; // eyes wink/blink are handled separately
        }
        if (mapping && mapping[key]) {
          lerpMorphTarget(key, mapping[key], 0.1);
        } else {
          lerpMorphTarget(key, 0, 0.1);
        }
      });

    lerpMorphTarget("eyeBlinkLeft", blink || winkLeft ? 1 : 0, 0.5);
    lerpMorphTarget("eyeBlinkRight", blink || winkRight ? 1 : 0, 0.5);

    // LIPSYNC
    if (setupMode) {
      return;
    }

    const appliedMorphTargets = [];
    if (message && lipsync && audioInstance) {
      const currentAudioTime = audioInstance.currentTime;
      for (let i = 0; i < lipsync.mouthCues.length; i++) {
        const mouthCue = lipsync.mouthCues[i];
        if (
          currentAudioTime >= mouthCue.start &&
          currentAudioTime <= mouthCue.end
        ) {
          appliedMorphTargets.push(corresponding[mouthCue.value]);
          lerpMorphTarget(corresponding[mouthCue.value], 1, 0.2);
          break;
        }
      }
    }

    Object.values(corresponding).forEach((value) => {
      if (appliedMorphTargets.includes(value)) {
        return;
      }
      lerpMorphTarget(value, 0, 0.1);
    });
  });

  useControls("FacialExpressions", {
    chat: button(() => chat()),
    winkLeft: button(() => {
      setWinkLeft(true);
      setTimeout(() => setWinkLeft(false), 300);
    }),
    winkRight: button(() => {
      setWinkRight(true);
      setTimeout(() => setWinkRight(false), 300);
    }),
    animation: {
      value: animation,
      options: animations.map((a) => a.name),
      onChange: (value) => setAnimation(value),
    },
    facialExpression: {
      options: Object.keys(facialExpressions),
      onChange: (value) => setFacialExpression(value),
    },
    enableSetupMode: button(() => {
      setupMode = true;
    }),
    disableSetupMode: button(() => {
      setupMode = false;
    }),
    logMorphTargetValues: button(() => {
      const emotionValues = {};
      Object.keys(nodes.EyeLeft.morphTargetDictionary).forEach((key) => {
        if (key === "eyeBlinkLeft" || key === "eyeBlinkRight") {
          return; // eyes wink/blink are handled separately
        }
        const value =
          nodes.EyeLeft.morphTargetInfluences[
            nodes.EyeLeft.morphTargetDictionary[key]
          ];
        if (value > 0.01) {
          emotionValues[key] = value;
        }
      });
      console.log(JSON.stringify(emotionValues, null, 2));
    }),
  });

  const [, set] = useControls("MorphTarget", () =>
    Object.assign(
      {},
      ...Object.keys(nodes.EyeLeft.morphTargetDictionary).map((key) => {
        return {
          [key]: {
            label: key,
            value: 0,
            min: nodes.EyeLeft.morphTargetInfluences[
              nodes.EyeLeft.morphTargetDictionary[key]
            ],
            max: 1,
            onChange: (val) => {
              if (setupMode) {
                lerpMorphTarget(key, val, 1);
              }
            },
          },
        };
      })
    )
  );

  return (
     <group {...props} dispose={null} ref={group}>
      <primitive object={nodes.Hips} />
      <skinnedMesh
        name="EyeLeft"
        geometry={nodes.EyeLeft.geometry}
        material={materials.Wolf3D_Eye}
        skeleton={nodes.EyeLeft.skeleton}
        morphTargetDictionary={nodes.EyeLeft.morphTargetDictionary}
        morphTargetInfluences={nodes.EyeLeft.morphTargetInfluences}
      />
      <skinnedMesh
        name="EyeRight"
        geometry={nodes.EyeRight.geometry}
        material={materials.Wolf3D_Eye}
        skeleton={nodes.EyeRight.skeleton}
        morphTargetDictionary={nodes.EyeRight.morphTargetDictionary}
        morphTargetInfluences={nodes.EyeRight.morphTargetInfluences}
      />
      <skinnedMesh
        name="Wolf3D_Head"
        geometry={nodes.Wolf3D_Head.geometry}
        material={materials.Wolf3D_Skin}
        skeleton={nodes.Wolf3D_Head.skeleton}
        morphTargetDictionary={nodes.Wolf3D_Head.morphTargetDictionary}
        morphTargetInfluences={nodes.Wolf3D_Head.morphTargetInfluences}
      />
      <skinnedMesh
        name="Wolf3D_Teeth"
        geometry={nodes.Wolf3D_Teeth.geometry}
        material={materials.Wolf3D_Teeth}
        skeleton={nodes.Wolf3D_Teeth.skeleton}
        morphTargetDictionary={nodes.Wolf3D_Teeth.morphTargetDictionary}
        morphTargetInfluences={nodes.Wolf3D_Teeth.morphTargetInfluences}
      />
      <skinnedMesh
        geometry={nodes.Wolf3D_Hair.geometry}
        material={materials.Wolf3D_Hair}
        skeleton={nodes.Wolf3D_Hair.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Wolf3D_Body.geometry}
        material={materials.Wolf3D_Body}
        skeleton={nodes.Wolf3D_Body.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Wolf3D_Outfit_Bottom.geometry}
        material={materials.Wolf3D_Outfit_Bottom}
        skeleton={nodes.Wolf3D_Outfit_Bottom.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Wolf3D_Outfit_Footwear.geometry}
        material={materials.Wolf3D_Outfit_Footwear}
        skeleton={nodes.Wolf3D_Outfit_Footwear.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Wolf3D_Outfit_Top.geometry}
        material={materials.Wolf3D_Outfit_Top}
        skeleton={nodes.Wolf3D_Outfit_Top.skeleton}
      />
    </group>
  )
}

// useGLTF.preload("/models/gisca2.glb");
// useGLTF.preload("/models/64f1a714fe61576b46f27ca2.glb");
useGLTF.preload("/models/geriarti.glb");
// useGLTF.preload("/models/66d6c1a81397d69042391d81_new.glb");
useGLTF.preload("/models/geriarti-animation.glb");
